### ISSUE TITLE
Deploy DAMS Manager 2.55 and Jolly Roger 1.12

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/damsmanager#143] opened 2017-04-14 21:10 UTC
DAMS Manager Version: 2.55
Jolly Roger Version: 1.12
Release Manager: @lsitu 
Product Owner and Reviewers: @gamontoya @GregReser 
Operations: @rstanonik 

Review Checklist:
- [x] #138 
- [x] #140

**Comment by mcritchlow** [comment] 2017-04-14 21:10
@lsitu and @rstanonik the deploy of Jolly Roger and DAMS Manager are tied together, so I think it's probably simpler to just track that in this one ticket. If that's ok with you all.

**Comment by lsitu** [comment] 2017-04-14 22:05
@rstanonik Is auto deploy to staging with the staging tag "git tag -a -f staging -m 'release 2.55'" still working? I tagged it for damsmanager and JollyRoger more than half of an hour ago but I don't received any emails for the deployment status as I used to. Thanks.

**Comment by lsitu** [comment] 2017-04-14 23:26
@gamontoya @GregReser The new releases for DAMS Manager and JollyRoger are deployed to staging and it's ready for review now. Thanks @rstanonik for setting up the Jenkins plans and deploy both apps to staging.

**Comment by lsitu** [comment] 2017-04-21 20:17
@gamontoya @GregReser Does damsmanager and JollyRoger ready for prod deployment?

**Comment by mcritchlow** [comment] 2017-04-25 16:22
@GregReser have you had a chance to review this? We've had these apps queued for release for almost two weeks now. I know @gamontoya is out this week, and if you're swamped, maybe someone else could help review?

**Comment by GregReser** [comment] 2017-04-26 18:20
@mcritchlow I'll test this today

**Comment by GregReser** [comment] 2017-04-26 21:46
@mcritchlow confirmed that #138 and #140 are working as expected.  This is ready for prod deployment.

**Comment by mcritchlow** [comment] 2017-04-26 21:47
@GregReser Thank you!

**Comment by lsitu** [comment] 2017-04-26 22:31
@gamontoya Should we move damsmanager and JollyRoger to prod now? Thanks.

**Comment by mcritchlow** [comment] 2017-04-26 22:33
@lsitu I think given how long we've had these open, and that @gamontoya is out and @GregReser did all the testing and verification, we can move forward with deploying in this case.

**Comment by lsitu** [comment] 2017-04-26 22:49
@rstanonik I've merged release/2.55 for damsmanager to the master branch, and I also merged Jolly Roger release/1.12 to the master branch as well. Both damsmanager and Jolly Roger are ready for prod now. Thanks.

**Comment by lsitu** [comment] 2017-04-27 19:19
@rstanonik The deployment looks good. Thanks. Could we close the deployment ticket now?

**Comment by lsitu** [comment] 2017-05-01 16:23
Close the ticket now since the deployment is done.

**Closed by lsitu** 2017-05-01 16:23 UTC
Labels: deploy
