### ISSUE TITLE
Batch metadata overlay: testing on staging server

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsmanager#345] opened 2019-07-11 21:48 UTC
### Descriptive summary

Testing for new batch overlay functionality - issues #321 #322 #323 #324
Also testing of existing excel ingest functionality ([due to code refactoring](https://github.com/ucsdlib/damsmanager/issues/339#issuecomment-510143027))

### Related work
#321 
#322
#323
#324

### Part of Batch edit functionality (epic) #309

**Comment by arwenhutt** [comment] 2019-07-11 21:56
## 1. Unable to ingest tracer record in staging
This ingests to production https://library.ucsd.edu/dc/object/bb38955027 may not be indexed yet but rdf is visible) but fails in staging.
Error message in DAMS Manager UI
![image](https://user-images.githubusercontent.com/16270512/61087745-634acf80-a3eb-11e9-8f65-10c789191616.png)


Interestingly I was able to ingest another "real" record to staging: https://librarytest.ucsd.edu/dc/object/bd2410911r

### Ingest file and DAMS manager invocation report locations:
Tracer record:
- Metadata & report: /rdcp-staging/zz_Test/batch_edit/Arwen/old tracer
- Files: /rdcp-staging/zz_Test/batch_edit/Arwen/files

Soccom object:
- Metadata & report: /rdcp-staging/rdcp-0090/Final_Metadata
- Files: /rdcp-staging/rdcp-0090/Final_Files

**Comment by arwenhutt** [comment] 2019-07-12 17:00
@lsitu & @gamontoya just an fyi that much of our testing is dependent upon being able to ingest tracer records, so we're in a holding pattern until the first bug is figured out.

**Comment by lsitu** [comment] 2019-07-12 19:17
Thanks @arwenhutt. I've fixed the error with CulturalContext conversion that causes the old tracer record failed to be ingested. I also refactored the codes to separate the control values for Excel Import and Batch Overlay to have their own set of CVs for validation.
@mcritchlow I've created PR https://github.com/ucsdlib/damsmanager/pull/346 for it. It's ready for review now. Thanks.

**Comment by lsitu** [comment] 2019-07-12 19:59
Thanks @mcritchlow for giving such a quick review on PR https://github.com/ucsdlib/damsmanager/pull/346.
@arwenhutt I've deployed PR https://github.com/ucsdlib/damsmanager/pull/346 to staging, which will fix the problem you ran into while ingesting the old tracer record. Could you to test it again when you got a chance? Thank you.

**Comment by remerjohnson** [comment] 2019-07-12 23:03
I'm not sure if this is user error on my part or not, but upon submitting a changed record via Batch Import, it passed initially, but seemingly is querying for the "old" unique object ID and 404s out? 

```
Pre-processing failed: 

 
Original object 02--The 'original'--PART NAME--PART NUMBER - bd5858045c -  successful - 2019-07-12T15:36:17


[Object] - 1001 -  failed - 2019-07-12T15:36:17 - 
* GET https://lib-hydratail-staging.ucsd.edu:8443/dams/api/objects/1001?format=xml&ts=dams&priority=4&user=rejohnson:  2019-07-12T03:36:17-0700 status code 404. Error Object does not exist
```

**Comment by arwenhutt** [comment] 2019-07-13 00:12
@remerjohnson verified that it now ingests the tracer record.
Thanks @lsitu!

**Comment by lsitu** [comment] 2019-07-15 15:25
@arwenhutt / @remerjohnson We've deployed PR https://github.com/ucsdlib/damsmanager/pull/346 to staging and I think those additional fields for batch overlay will be validated now. Could you give it a try to test Batch edit again? Thanks.

**Comment by arwenhutt** [comment] 2019-07-15 19:03
@lsitu yep, we'll continue testing.

**Comment by arwenhutt** [comment] 2019-07-17 18:27
@lsitu 
## 2. Component and sub-component titles lost or overwritten with the object title on ingest
### SOCCOM example
 - Staging: https://librarytest.ucsd.edu/dc/object/bd2410911r
 - Production: https://library.ucsd.edu/dc/object/bb7786316t

They both used the same metadata and files:
- Metadata: /rdcp-staging/rdcp-0090/Final_Metadata
- Files: /rdcp-staging/rdcp-0090/Final_Files

### STEM undergraduate participation example
- Staging: https://librarytest.ucsd.edu/dc/object/bd57215347
- Production: https://library.ucsd.edu/dc/object/bb6147997d

They both used the same metadata and files:
- Metadata: X:\rdcp-0153-STEM-undergrad-participation\Final_Metadata
- Files: X:\rdcp-0153-STEM-undergrad-participation\Final_Files

**Comment by lsitu** [comment] 2019-07-17 20:11
@arwenhutt Good catch! Thanks. I've created PR https://github.com/ucsdlib/damsmanager/pull/347 to fix it. Once the PR is reviewed and merged, I'll deploy it to staging for you to review. @mcritchlow The PR is ready for review now. Thanks.

**Comment by lsitu** [comment] 2019-07-17 21:14
Thanks @mcritchlow for the a quick review of the PR. @arwenhutt I've deployed it to staging and it's ready for test now. Thank you.

**Comment by arwenhutt** [comment] 2019-07-17 21:49
@lsitu I just ingested the SOCCOM object again and the titles look good!  Thanks!

**Comment by lsitu** [comment] 2019-07-18 18:28
@mcritchlow I added PR https://github.com/ucsdlib/damsmanager/pull/348 to fix the `java.lang.UnsupportedOperationException` found by Ryan during collection import, which is caused by the fixed size list support in Java. Could you review and merge it if you get a chance? Thanks @remerjohnson.

**Comment by lsitu** [comment] 2019-07-18 18:48
Thanks @mcritchlow for the quick review.
@arwenhutt / @remerjohnson I've deployed the PR to staging to fix that `java.lang.UnsupportedOperationException` issue with collection import. It's ready for test on staging now. Thanks.

**Comment by remerjohnson** [comment] 2019-07-18 19:16
@lsitu Yes, the `java.lang.UnsupportedOperationException` error has gone away, and I was able to ingest two different CLRs. Thanks

**Comment by arwenhutt** [comment] 2019-07-24 23:58
@lsitu & @gamontoya Just a quick update, we've finished our planned batch ingest testing and haven't found any other issues there.  With that done, we resumed batch overlay testing this afternoon.

**Comment by arwenhutt** [comment] 2019-07-25 19:10
@lsitu 
## 3. Component and sub-component metadata edits applied to the wrong level

### Example
When editing complex objects, the metadata gets "scrambled" - sub-component metadata is written to components, component metadata sometimes disappears (overwritten I'm guessing), and sub-components metadata isn't changed (when it should be.)

We are wondering if it has something to do with the `Object Unique ID`  values which don't seem to line up with the component numbering in the rdf?

I tried editing the `Object Unique ID` values in an overlay spreadsheet to match those shown in the rdf but, then got an error messages like this for each row: 
> 2019-07-25T11:34:01-0700 status code 404. Error Object does not exist [Object] - bd1557737c/1 - failed - 2019-07-25T11:34:01 -

 - After overlay: https://librarytest.ucsd.edu/dc/object/bd9783066t
 - Duplicate ingest of what the record above looked like before overlay: https://librarytest.ucsd.edu/dc/object/bd2854678g

- Test files: X:\zz_Test\batch_edit\Arwen\ae5 component subcomponent

**Comment by abbypenn93** [comment] 2019-07-25 20:42
**Regarding 3. Component and sub-component metadata edits applied to the wrong level**: Changes were correctly applied during Batch Edit after manual edit of the Sub-component Object Unique ID. Batch Export originally wrote the ARKs as Object:  bd9510029v, Component: bd9510029v/1, Sub-component: bd9510029v/1. Changing the Sub-component Object ID to bd9510029v/2 and rerunning Batch Edit resulted in the correct display of component and sub-component metadata.




bd9510029v
--




bd9510029v
--

**Comment by lsitu** [comment] 2019-07-25 21:35
Thanks @arwenhutt and @abbypenn93 for the additional information. I've found the issue in Batch Export and created PR https://github.com/ucsdlib/damsmanager/pull/353 to fix it.
@mcritchlow Could you review PR https://github.com/ucsdlib/damsmanager/pull/353 when you got a chance? Thank you.

**Comment by lsitu** [comment] 2019-07-25 22:24
Thanks @mcritchlow for the quick review.
@arwenhutt / @abbypenn93 I've deployed the PR that fix the Batch Export `Unique Object ID` for Sub-component ` to staging. Could you export the collection with complex objects and test the batch overlay support again? Thank you.

**Comment by arwenhutt** [comment] 2019-07-25 22:41
@lsitu yay!  It worked: https://librarytest.ucsd.edu/dc/object/bd9783066t is all fixed and everything in order.  Thanks!

**Comment by arwenhutt** [comment] 2019-07-31 23:58
@lsitu & @mcritchlow I think we're done with testing! There are a few things that came up in the last rounds, but I don't think any of them are blockers and could be fixed after the production release.

**Comment by lsitu** [comment] 2019-08-01 00:31
@arwenhutt Thanks for the hard work. We'll push damsmanager Release 2.72 to prod then. @mcritchlow Do you have any concerns for pushing it to prod now? Thanks.

**Comment by mcritchlow** [comment] 2019-08-01 16:19
@lsitu - with the feedback you've gotten, i'd say ship it! :rocket:

**Comment by arwenhutt** [comment] 2020-01-14 18:09
@gamontoya I think we can close this and the epic ticket.  While there are some remaining blips we discover those can be added as standalone tickets (bug reports or enhancement requests as appropriate.)  What do you think?

**Comment by gamontoya** [comment] 2020-01-14 18:46
@arwenhutt Sounds good to me!

**Closed** 2020-01-14 18:46 UTC
