### ISSUE TITLE
CIL Harvesting - Retrieve initial batch of master source files from CIL's Public REST API

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damsmanager#327] opened 2019-05-20 18:57 UTC
### Descriptive summary

Please try our API again. See https://github.com/CRBS/CIL_RS/wiki/CIL_Public_API

Example:
curl -XGET -u ucsd_lib:yrDMRoZzOfmlHQU "https://cilia.crbs.ucsd.edu/rest/public_ids?from=0&size=1&lastModified=1285905600"

### Rationale

The CIL (http://www.cellimagelibrary.org) has made data available through their public API. We want to harvest all of their current metadata and image files for an initial batch ingest. In subsequent work, we'll need to continue to ingest new items from CIL.

### Related work

Metadata mapping: https://github.com/ucsdlib/damsmanager/issues/289
Previous harvest work (obsolete method): https://github.com/ucsdlib/damsmanager/issues/297
Epic: https://github.com/ucsdlib/damsmanager/issues/316

**Comment by lsitu** [comment] 2019-05-28 18:08
@hjsyoo It look like that the CIL's Public REST API requires authentication. Do you have the account that we can use to pull the JSON data? Thanks.

**Comment by lsitu** [comment] 2019-05-29 16:56
@hjsyoo Is the CIL API (https://cilia.crbs.ucsd.edu/rest) ready for us? It looks like it always return 9681 total hits regardless what lastModified timestamp it is. For example:
1. Test with timestamp lastModified=1559147762017 (Wed May 29 09:36:02 PDT 2019) get total hits 9681:
```
$ curl -XGET -u ucsd_lib:yrDMRoZzOfmlHQU "https://cilia.crbs.ucsd.edu/rest/public_ids?from=0&size=0&lastModified=1559147762017"
```
Results:
```
{"took":0,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":9681,"max_score":0,"hits":[]}}
```

2. Test with timestamp lastModified=959618162016 (Mon May 29 09:36:02 PDT 2000) get the same total hits 9681:
```
$ curl -XGET -u ucsd_lib:yrDMRoZzOfmlHQU "https://cilia.crbs.ucsd.edu/rest/public_ids?from=0&size=0&lastModified=959618162016"
```
Results:
```
{"took":0,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":9681,"max_score":0,"hits":[]}}
```

So the results are the same since Monday, May 29 2000 and there are no changes since then.

**Comment by lsitu** [comment] 2019-05-29 20:59
@hjsyoo I found the problems now and please ignore my question above. I think I was using milliseconds in my tests above while the CIL API is expecting seconds instead.
Is 9681  the total CIL objects that we have so far or something like 10,023 JSONs as in https://github.com/ucsdlib/damsmanager/issues/317#issuecomment-489270362?

**Comment by abbypenn93** [comment] 2019-05-29 22:04
10,023 json files were in what I believe is the most recent download, dated 2-21-2009.

**Comment by hjsyoo** [comment] 2019-05-29 22:14
@abbypenn93 Sorry - I'm in a workshop this week, but where are these files located?

**Comment by abbypenn93** [comment] 2019-05-29 22:56
The 10,023 json files are located in rdcp-0126-cil/cil_harvest_2019-03-07/metadata_source (sorry, i cited the wrong date above)

**Comment by lsitu** [comment] 2019-05-30 15:34
@hjsyoo It looks like the format of JSON source retrieved from CIL API is a little different from the version in the Github repository https://github.com/slash-segmentation/CIL_Public_Data_JSON, which is wrapping the source data under the `_source` key.
Here is the JSON retrieved from CIL API for object 50512:
`$ curl -XGET -u ucsd_lib:yrDMRoZzOfmlHQU "https://cilia.crbs.ucsd.edu/rest/public_documents/CIL_50512"`
```
{"_index":"ccdbv8","_type":"data","_id":"CIL_50512","_version":9,"found":true,"_source":{"CIL_CCDB":{"Status":{"Deleted":false,"Is_public":true,"Publish_time":1557450900},"CIL":{"CORE":{"IMAGEDESCRIPTION":{"free_text":"We examined the structural organization of cytoskeletal ..."},"TECHNICALDETAILS":{"free_text":"We observed several interesting ultrastructural features in AD neurons. ..."},"NCBIORGANISMALCLASSIFICATION":[{"onto_id":"NCBITaxon:9606","onto_name":"Homo sapiens"}],"CELLULARCOMPONENT":[{"onto_id":"GO:0005634","onto_name":"nucleus"},{"onto_id":"GO:0005730","onto_name":"nucleolus"},{"onto_id":"GO:0005886","onto_name":"plasma membrane"},{"onto_id":"GO:0044431","onto_name":"Golgi apparatus part"},{"free_text":"paired helical filaments"}],"IMAGINGMODE":[{"free_text":"serial section TEM"}],"ATTRIBUTION":{"Contributors":["Mark Ellisman","Rama Ranganathan","Thomas Deerinck","Stephen Young","David Hessler","Robert Terry"],"URLs":[{"Label":"Article","Href":"https:\/\/link.springer.com\/chapter\/10.1007\/978-1-4613-1657-2_6"}]},"ITEMTYPE":[{"onto_id":"FBbi:00000265","onto_name":"recorded image"}],"TERMSANDCONDITIONS":{"free_text":"public_domain"},"HUMAN_DISEASE":[{"onto_id":"DOID:10652","onto_name":"Alzheimer's disease"}]},"Image_files":[{"Mime_type":"application\/zip","File_type":"Zip","File_path":"50512.zip","Size":15659136},{"Mime_type":"image\/jpeg; charset=utf-8","File_type":"Jpeg","File_path":"50512.jpg","Size":116024},{"Mime_type":"video\/x-flv","File_type":"Flv","File_path":"50512.flv","Size":1392086}]},"Data_type":{"Still_image":false,"Z_stack":false,"Time_series":false,"Video":true}}}}
```
Should we stored the whole JSON retrieved from the CIL API in `metadata_source` directory, or just extract the JSON content from the `_source` key like what we get from the Github repository, https://github.com/slash-segmentation/CIL_Public_Data_JSON?

Also, is there any change for retrieving content files? I can't find the information for content files retrieval in https://github.com/CRBS/CIL_RS/wiki/CIL_Public_API but thumbnails. From the Github repository, https://github.com/slash-segmentation/CIL_Public_Data_JSON, content files should be retrieved from `https://cildata.crbs.ucsd.edu/media/` basing on `$json->CIL_CCDB->Data_type`. For example, https://cildata.crbs.ucsd.edu/media/videos/50512/50512.jpg for object 50512 above.
But it seem like some content files may not be there and I got status 404 from the video/x-flv file https://cildata.crbs.ucsd.edu/media/videos/50512/50512.flv:
```
$ curl -XGET -u ucsd_lib:yrDMRoZzOfmlHQU "https://cildata.crbs.ucsd.edu/media/videos/50512/50512.flv"
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /media/videos/50512/50512.flv was not found on this server.</p>
</body></html>
```

**Comment by lsitu** [comment] 2019-06-04 15:38
@hjsyoo / @arwenhutt Do you have any suggestions for the issues in my comment https://github.com/ucsdlib/damsmanager/issues/327#issuecomment-497373874 above? Thank you.

**Comment by arwenhutt** [comment] 2019-06-04 16:59
@lsitu For your first question about the metadata_source files, I think the second option makes more sense
> "just extract the JSON content from the _source key like what we get from the Github repository, https://github.com/slash-segmentation/CIL_Public_Data_JSON?"

**Comment by arwenhutt** [comment] 2019-06-04 17:16
@lsitu for your second question - are you saying that the method (previously implemented in [#297](https://github.com/ucsdlib/damsmanager/issues/297)) no longer works?

**Comment by lsitu** [comment] 2019-06-04 18:29
@arwenhutt This a new implementation in DAMS Manager for the CIL public API download. I think  the problem is that some content files are missing from the portal `https://cildata.crbs.ucsd.edu/` that is used to download content files in https://github.com/ucsdlib/damsmanager/issues/297. For example, https://cildata.crbs.ucsd.edu/media/videos/50512/50512.flv. But I am not sure whether there are any changes to it recently that causes the problem, or there will be a corresponding public API for downloading the content files through portal `https://cilia.crbs.ucsd.edu/rest`, something like the support for downloading thumbnails for display purpose.

**Comment by arwenhutt** [comment] 2019-06-04 21:48
@lsitu sorry, I'm not aware of any changes, but I'm also not completely clear on the question.  I had thought that the file transfer piece from the previous implementation was still viable but I could be wrong about that.  

Maybe @hjsyoo knows more?

**Comment by lsitu** [comment] 2019-06-04 22:42
@arwenhutt / @hjsyoo Thanks. Then I am assuming that the original portal `https://cildata.crbs.ucsd.edu/` for content files download (see https://github.com/slash-segmentation/CIL_Public_Data_JSON) is still valid and I'll simply apply it for the new JSON source download implementation from the CIL public API.

**Comment by hjsyoo** [comment] 2019-06-04 22:51
@lsitu I’m not aware of any changes either! I’m away from the office at the moment, but will ask Willy about the missing data as soon as I get back and will cc you on the thread.

**Comment by lsitu** [comment] 2019-06-06 16:12
@mcritchlow / @hjsyoo Basing on the feedbacks from Willy, I've created the following two PRs to support CIL REST API download:
https://github.com/ucsdlib/damsmanager/pull/330
https://github.com/ucsdlib/private_config/pull/14

Both PRs are ready for review now. Thanks.

**Comment by hjsyoo** [comment] 2019-06-06 18:37
Thanks, @lsitu. Please let me know when the call seems to work and you're ready for @arwenhutt and me to review the harvested content and JSON source files.

**Comment by lsitu** [comment] 2019-06-06 20:12
@hjsyoo Sure thing. I think we can start another round of QA once the PR get merged. But we can't start the process to download the JSON until Willy have the metadata updated for videos:
```
From: willy wong <wawong@gmail.com>
Sent: Tuesday, June 4, 2019 6:15 PM
To: Situ, Longshou
Cc: Yoo, Ho Jung; Hutt, Arwen
Subject: Re: CIL transfer/ingest workflow
 
Hi Longshou,

I see the problem. The JSON content is not consistent with the file locations. For now, can you skip all "Video" type datasets? I will correct the metadata and notify you guys when it is done. We have migrated all of our Flash videos to the MP4 videos but the metadata have not reflected those changes yet.

Thank you,
Willy
```

Could you let me know once we can start to download JSON source from the REST API? Thanks.

**Closed** 2019-06-07 16:19 UTC
Labels: rdcp

**Comment by lsitu** [comment] 2019-06-14 19:32
@mcritchlow Basing on the recent changes of the CIL public API and the response from Willy, I've add PR https://github.com/ucsdlib/damsmanager/pull/333 to fix the GTE search results with  lastModified. It's ready for review now. Thanks.
